import React from 'react'
import { Link } from 'react-router-dom'
import LegalDoc from './LegalDoc.jsx'

export default function Terms() {
  return (
    <LegalDoc
      title="Terms of Service"
      description="The terms governing your use of Influensa."
      path="/terms"
      updated="15 June 2026">
      <p>
        These Terms of Service ("Terms") govern your access to and use of Influensa (the "Service"),
        operated by <strong>[LEGAL ENTITY NAME]</strong> ("we", "us"). By creating an account or using
        the Service, you agree to these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>1. Eligibility &amp; accounts</h2>
      <p>
        You must be at least 18 years old (or the age of majority in your jurisdiction) to use Influensa.
        You are responsible for your account credentials and for all activity under your account. Authentication
        is handled by Clerk; you agree to their handling of your sign-in data.
      </p>

      <h2>2. The Service</h2>
      <p>
        Influensa provides AI-assisted content tools — trend discovery across public sources (YouTube, Reddit)
        and AI-generated scripts. Outputs are generated by AI models and may be inaccurate; you are responsible
        for reviewing and for how you use them.
      </p>

      <h2>3. Acceptable use</h2>
      <ul>
        <li>No unlawful, infringing, hateful, or harmful content.</li>
        <li>No attempts to reverse engineer, scrape, overload, or bypass usage limits or security.</li>
        <li>No resale or redistribution of the Service without written permission.</li>
      </ul>

      <h2>4. Subscriptions, billing &amp; renewals</h2>
      <p>
        Paid plans are billed via Razorpay on a recurring basis (monthly or yearly) and <strong>auto-renew</strong>
        until cancelled. Prices are listed on our <Link to="/pricing">pricing page</Link> and are exclusive of
        applicable taxes unless stated. You authorise us and Razorpay to charge your payment method each cycle.
        You can cancel anytime; see our <Link to="/refund">Refund &amp; Cancellation Policy</Link>.
      </p>

      <h2>5. Your content</h2>
      <p>
        You retain ownership of the content you create. You grant us a limited licence to process your inputs
        (e.g., captions, prompts) solely to operate and improve the Service, including sending them to our AI
        processor (Google Vertex AI / Gemini). We do not sell your content.
      </p>

      <h2>6. Intellectual property</h2>
      <p>
        The Service, including its software, design, and branding, is owned by us and protected by law. These
        Terms grant you no rights to our trademarks or code beyond using the Service as intended.
      </p>

      <h2>7. Disclaimers &amp; liability</h2>
      <p>
        The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law,
        our aggregate liability is limited to the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>8. Termination</h2>
      <p>
        You may stop using the Service at any time. We may suspend or terminate accounts that violate these Terms.
      </p>

      <h2>9. Governing law</h2>
      <p>
        These Terms are governed by the laws of India, with exclusive jurisdiction in the courts of
        <strong> [CITY, STATE]</strong>.
      </p>

      <h2>10. Changes &amp; contact</h2>
      <p>
        We may update these Terms; material changes will be posted here with a new date. Questions?
        Reach us via our <Link to="/contact">contact page</Link> or at <a href="mailto:support@influensa.xyz">support@influensa.xyz</a>.
      </p>
    </LegalDoc>
  )
}
