// Creator glossary. Each entry becomes an indexable /glossary/:slug page —
// great for "what is X" long-tail queries and AI-search citations.

export const TERMS = [
  {
    slug: 'engagement-velocity',
    term: 'Engagement velocity',
    short: 'How fast a piece of content gains engagement over time, not its total.',
    definition: 'Engagement velocity measures the rate at which a post accumulates likes, comments, and shares — typically per hour in its early life. It is a leading indicator of virality: a topic with high velocity is rising and worth acting on, even if its absolute numbers are still small. Creators use velocity to catch trends before they peak, rather than reacting to lifetime view counts that only confirm what already won.',
  },
  {
    slug: 'hook-rate',
    term: 'Hook rate',
    short: 'The share of viewers who keep watching past the first few seconds.',
    definition: 'Hook rate is the percentage of viewers retained through the opening seconds of a short-form video (often the first 3 seconds). It is the single biggest lever in short-form performance: a weak hook caps your reach no matter how good the rest is. Improving hook rate usually means making the opening more specific, creating a curiosity gap, or leading with the payoff.',
  },
  {
    slug: 'content-pillar',
    term: 'Content pillar',
    short: 'A recurring theme that organises what a creator makes.',
    definition: 'A content pillar is one of a small set of core topics a creator returns to consistently. Pillars give an audience a clear reason to follow and help the algorithm understand your niche. Most creators run three to five pillars and rotate formats within each, balancing reliability with variety.',
  },
  {
    slug: 'viral-coefficient',
    term: 'Viral coefficient',
    short: 'How many new viewers each viewer brings, on average.',
    definition: 'The viral coefficient is the average number of additional viewers generated by each existing viewer through shares and re-posts. A coefficient above one implies self-sustaining growth. For creators it is a useful mental model: content engineered to be shared (saves, sends, duets) compounds far faster than content optimised only for passive views.',
  },
  {
    slug: 'watch-time',
    term: 'Watch time',
    short: 'Total time audiences spend watching your content.',
    definition: 'Watch time is the aggregate duration viewers spend on your videos. Platforms weight it heavily because it reflects genuine attention and keeps users on the app. Both average view duration and completion rate feed into it, which is why pacing, retention hooks, and tight editing matter more than length alone.',
  },
]

export const getTerm = (slug) => TERMS.find(t => t.slug === slug)
