/**
 * Niche definitions — single source of truth.
 * Used in onboarding, dashboard niche picker, scraping, profile.
 */

export const NICHE_CATEGORIES = [
  {
    id: 'business',
    label: 'Business & Money',
    niches: [
      { id: 'finance',      label: 'Personal Finance',  icon: '💰', color: '#F5EBCF' },
      { id: 'investing',    label: 'Investing',          icon: '📈', color: '#E8F5E3' },
      { id: 'crypto',       label: 'Crypto & Web3',      icon: '₿',  color: '#FFF3E0' },
      { id: 'ecommerce',    label: 'E-commerce',         icon: '🛒', color: '#F3E8FF' },
      { id: 'marketing',    label: 'Marketing',          icon: '📣', color: '#FCE4EC' },
      { id: 'side-hustle',  label: 'Side Hustle',        icon: '💡', color: '#E8F5E3' },
      { id: 'real-estate',  label: 'Real Estate',        icon: '🏠', color: '#E3F2FD' },
      { id: 'startup',      label: 'Startups',           icon: '🚀', color: '#EDE9FE' },
      { id: 'career',       label: 'Career & Jobs',      icon: '💼', color: '#FFF9C4' },
    ],
  },
  {
    id: 'health',
    label: 'Health & Fitness',
    niches: [
      { id: 'fitness',      label: 'Fitness',            icon: '💪', color: '#E5EBDB' },
      { id: 'yoga',         label: 'Yoga',               icon: '🧘', color: '#F3E8FF' },
      { id: 'running',      label: 'Running',            icon: '🏃', color: '#E0F2F1' },
      { id: 'nutrition',    label: 'Nutrition',          icon: '🥗', color: '#E8F5E3' },
      { id: 'weight-loss',  label: 'Weight Loss',        icon: '⚖️', color: '#FFF9C4' },
      { id: 'mental-health',label: 'Mental Health',      icon: '🧠', color: '#E8EAF6' },
      { id: 'meditation',   label: 'Meditation',         icon: '🌸', color: '#FCE4EC' },
      { id: 'veganism',     label: 'Veganism',           icon: '🌱', color: '#E8F5E3' },
      { id: 'bodybuilding', label: 'Bodybuilding',       icon: '🏋️', color: '#F5EBCF' },
    ],
  },
  {
    id: 'beauty',
    label: 'Beauty & Fashion',
    niches: [
      { id: 'beauty',       label: 'Beauty',             icon: '💄', color: '#FCE7F3' },
      { id: 'skincare',     label: 'Skincare',           icon: '✨', color: '#FFF3E0' },
      { id: 'hair',         label: 'Hair Care',          icon: '💇', color: '#FCE4EC' },
      { id: 'fashion',      label: 'Fashion',            icon: '👗', color: '#F3E8FF' },
      { id: 'nails',        label: 'Nails',              icon: '💅', color: '#FCE7F3' },
      { id: 'streetwear',   label: 'Streetwear',         icon: '👟', color: '#E8EAF6' },
    ],
  },
  {
    id: 'food',
    label: 'Food & Cooking',
    niches: [
      { id: 'cooking',      label: 'Cooking',            icon: '👨‍🍳', color: '#FFF9C4' },
      { id: 'baking',       label: 'Baking',             icon: '🧁', color: '#FCE4EC' },
      { id: 'meal-prep',    label: 'Meal Prep',          icon: '🥡', color: '#E8F5E3' },
      { id: 'food',         label: 'Food & Foodie',      icon: '🍜', color: '#FCE7F3' },
      { id: 'keto',         label: 'Keto Diet',          icon: '🥩', color: '#F5EBCF' },
      { id: 'plant-based',  label: 'Plant-Based',        icon: '🥦', color: '#E8F5E3' },
      { id: 'street-food',  label: 'Street Food',        icon: '🌮', color: '#FFF3E0' },
      { id: 'coffee',       label: 'Coffee',             icon: '☕', color: '#F5EBCF' },
    ],
  },
  {
    id: 'tech',
    label: 'Tech & Science',
    niches: [
      { id: 'tech',         label: 'Tech',               icon: '⚡', color: '#EDE9FE' },
      { id: 'ai',           label: 'AI & Machine Learning',icon: '🤖', color: '#E8EAF6' },
      { id: 'coding',       label: 'Coding',             icon: '💻', color: '#E3F2FD' },
      { id: 'gadgets',      label: 'Gadgets',            icon: '📱', color: '#F3E8FF' },
      { id: 'cybersecurity',label: 'Cybersecurity',      icon: '🔐', color: '#E8EAF6' },
      { id: 'science',      label: 'Science',            icon: '🔬', color: '#E0F2F1' },
      { id: 'space',        label: 'Space & Astronomy',  icon: '🚀', color: '#E8EAF6' },
    ],
  },
  {
    id: 'entertainment',
    label: 'Entertainment',
    niches: [
      { id: 'gaming',       label: 'Gaming',             icon: '🎮', color: '#EDE9FE' },
      { id: 'anime',        label: 'Anime',              icon: '🎌', color: '#FCE4EC' },
      { id: 'movies',       label: 'Movies & TV',        icon: '🎬', color: '#E3F2FD' },
      { id: 'music',        label: 'Music',              icon: '🎵', color: '#F3E8FF' },
      { id: 'books',        label: 'Books',              icon: '📚', color: '#FFF9C4' },
      { id: 'comedy',       label: 'Comedy & Memes',     icon: '😂', color: '#FFF3E0' },
      { id: 'sports',       label: 'Sports',             icon: '⚽', color: '#E8F5E3' },
      { id: 'cricket',      label: 'Cricket',            icon: '🏏', color: '#E8F5E3' },
      { id: 'esports',      label: 'Esports',            icon: '🏆', color: '#EDE9FE' },
    ],
  },
  {
    id: 'lifestyle',
    label: 'Lifestyle',
    niches: [
      { id: 'lifestyle',    label: 'Lifestyle',          icon: '✨', color: '#FEF3C7' },
      { id: 'productivity', label: 'Productivity',       icon: '⏱️', color: '#E8F5E3' },
      { id: 'minimalism',   label: 'Minimalism',         icon: '🪴', color: '#E0F2F1' },
      { id: 'luxury',       label: 'Luxury Living',      icon: '💎', color: '#FFF9C4' },
      { id: 'self-improvement', label: 'Self Improvement', icon: '🧗', color: '#F5EBCF' },
      { id: 'journaling',   label: 'Journaling',         icon: '📓', color: '#FCE4EC' },
      { id: 'stoicism',     label: 'Stoicism',           icon: '🏛️', color: '#E8EAF6' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Outdoors',
    niches: [
      { id: 'travel',       label: 'Travel',             icon: '🌍', color: '#DBEAFE' },
      { id: 'hiking',       label: 'Hiking & Trekking',  icon: '🥾', color: '#E8F5E3' },
      { id: 'camping',      label: 'Camping',            icon: '⛺', color: '#E8F5E3' },
      { id: 'photography',  label: 'Photography',        icon: '📸', color: '#E3F2FD' },
      { id: 'solo-travel',  label: 'Solo Travel',        icon: '🎒', color: '#FFF3E0' },
      { id: 'budget-travel',label: 'Budget Travel',      icon: '✈️', color: '#E8EAF6' },
    ],
  },
  {
    id: 'family',
    label: 'Family & Relationships',
    niches: [
      { id: 'parenting',    label: 'Parenting',          icon: '👨‍👩‍👧', color: '#FFF9C4' },
      { id: 'pets',         label: 'Pets',               icon: '🐾', color: '#FFF3E0' },
      { id: 'dogs',         label: 'Dogs',               icon: '🐶', color: '#FFF3E0' },
      { id: 'cats',         label: 'Cats',               icon: '🐱', color: '#FCE4EC' },
      { id: 'relationships',label: 'Relationships',      icon: '❤️', color: '#FCE4EC' },
      { id: 'pregnancy',    label: 'Pregnancy & Baby',   icon: '👶', color: '#FCE7F3' },
    ],
  },
  {
    id: 'creative',
    label: 'Creative & Arts',
    niches: [
      { id: 'art',          label: 'Art & Illustration', icon: '🎨', color: '#FCE4EC' },
      { id: 'design',       label: 'Design & UI/UX',     icon: '🖌️', color: '#E8EAF6' },
      { id: 'diy',          label: 'DIY & Crafts',       icon: '🔨', color: '#FFF9C4' },
      { id: 'interior-design', label: 'Interior Design', icon: '🛋️', color: '#F3E8FF' },
      { id: 'writing',      label: 'Writing',            icon: '✍️', color: '#E3F2FD' },
      { id: 'architecture', label: 'Architecture',       icon: '🏛️', color: '#E8EAF6' },
    ],
  },
  {
    id: 'education',
    label: 'Education & Learning',
    niches: [
      { id: 'education',    label: 'Education',          icon: '🎓', color: '#E3F2FD' },
      { id: 'language-learning', label: 'Language Learning', icon: '🌐', color: '#E0F2F1' },
      { id: 'history',      label: 'History',            icon: '📜', color: '#F5EBCF' },
      { id: 'philosophy',   label: 'Philosophy',         icon: '🤔', color: '#EDE9FE' },
      { id: 'spirituality', label: 'Spirituality',       icon: '🕯️', color: '#FFF3E0' },
    ],
  },
]

/** Flat list — for backwards-compat and scraper lookups */
export const NICHES = NICHE_CATEGORIES.flatMap(cat => cat.niches)

export const NICHE_IDS = NICHES.map(n => n.id)

export const getNiche = (id) => NICHES.find(n => n.id === id)

/** Instagram hashtags per niche (no # prefix) */
export const NICHE_IG_HASHTAGS = {
  finance:        ['personalfinance', 'moneymanagement', 'financialtips', 'moneymindset', 'budgeting'],
  investing:      ['investing', 'stockmarket', 'dividends', 'wealthbuilding', 'passiveincome'],
  crypto:         ['crypto', 'bitcoin', 'ethereum', 'web3', 'cryptotrading'],
  ecommerce:      ['ecommerce', 'dropshipping', 'shopify', 'onlinebusiness', 'amazonFBA'],
  marketing:      ['digitalmarketing', 'contentmarketing', 'socialmediamarketing', 'seo', 'branding'],
  'side-hustle':  ['sidehustle', 'makemoneyonline', 'entrepreneurship', 'passiveincome', 'freelance'],
  'real-estate':  ['realestate', 'property', 'realestateinvesting', 'housing', 'landlord'],
  startup:        ['startup', 'entrepreneur', 'founder', 'innovation', 'venturecapital'],
  career:         ['career', 'jobsearch', 'resumetips', 'linkedin', 'professionaldevelopment'],
  fitness:        ['fitness', 'workout', 'gym', 'fitnessmotivation', 'bodybuilding'],
  yoga:           ['yoga', 'yogalife', 'yogapractice', 'yogainspiration', 'mindfulness'],
  running:        ['running', 'runningmotivation', 'marathon', 'runnersofinstagram', '5k'],
  nutrition:      ['nutrition', 'healthyfood', 'mealprep', 'healthyeating', 'cleaneating'],
  'weight-loss':  ['weightloss', 'weightlossjourney', 'fatloss', 'healthylifestyle', 'diet'],
  'mental-health':['mentalhealth', 'anxiety', 'selfcare', 'mentalhealthawareness', 'therapy'],
  meditation:     ['meditation', 'mindfulness', 'breathwork', 'innerpeace', 'zen'],
  veganism:       ['vegan', 'plantbased', 'veganfood', 'crueltyfree', 'govegan'],
  bodybuilding:   ['bodybuilding', 'powerlifting', 'gains', 'musclebuilding', 'lifting'],
  beauty:         ['beauty', 'skincare', 'makeup', 'beautycare', 'skincareroutine'],
  skincare:       ['skincare', 'glowingskin', 'skincareaddict', 'antiaging', 'acne'],
  hair:           ['haircare', 'hairstyle', 'naturalhair', 'hairgoals', 'hairtransformation'],
  fashion:        ['fashion', 'style', 'ootd', 'fashionblogger', 'outfitoftheday'],
  nails:          ['nails', 'nailart', 'manicure', 'gelmanicure', 'naildesign'],
  streetwear:     ['streetwear', 'hypebeast', 'sneakers', 'streetstyle', 'urbfashion'],
  cooking:        ['cooking', 'homecooking', 'recipes', 'foodphotography', 'cookingvideos'],
  baking:         ['baking', 'bakery', 'cakesofinstagram', 'homemade', 'bakedgoods'],
  'meal-prep':    ['mealprep', 'mealplanning', 'healthymeals', 'prepday', 'mealprepideas'],
  food:           ['food', 'foodie', 'foodphotography', 'instafood', 'foodlover'],
  keto:           ['keto', 'ketodiet', 'ketogenic', 'lowcarb', 'ketorecipes'],
  'plant-based':  ['plantbased', 'vegan', 'wholefood', 'plantbaseddiet', 'veganrecipes'],
  'street-food':  ['streetfood', 'foodie', 'localfood', 'foodhunt', 'eats'],
  coffee:         ['coffee', 'coffeelover', 'latteart', 'coffeetime', 'specialtycoffee'],
  tech:           ['technology', 'tech', 'innovation', 'futurism', 'gadgets'],
  ai:             ['artificialintelligence', 'machinelearning', 'ai', 'chatgpt', 'deeplearning'],
  coding:         ['coding', 'programming', 'developer', 'webdevelopment', 'codelife'],
  gadgets:        ['gadgets', 'tech', 'newtech', 'smartphone', 'techreview'],
  cybersecurity:  ['cybersecurity', 'hacking', 'infosec', 'privacy', 'datasecurity'],
  science:        ['science', 'physics', 'biology', 'chemistry', 'sciencefacts'],
  space:          ['space', 'astronomy', 'nasa', 'universe', 'cosmos'],
  gaming:         ['gaming', 'gamer', 'videogames', 'esports', 'pcgaming'],
  anime:          ['anime', 'otaku', 'manga', 'animefan', 'animeedits'],
  movies:         ['movies', 'cinema', 'film', 'moviereview', 'netflix'],
  music:          ['music', 'musician', 'newmusic', 'producer', 'musicvideo'],
  books:          ['books', 'reading', 'bookrecommendations', 'bookworm', 'booktok'],
  comedy:         ['comedy', 'funny', 'memes', 'humor', 'standup'],
  sports:         ['sports', 'fitness', 'athlete', 'sportslife', 'training'],
  cricket:        ['cricket', 'ipl', 'testcricket', 'cricketlovers', 'bcci'],
  esports:        ['esports', 'gaming', 'tournament', 'competitive', 'streamers'],
  lifestyle:      ['lifestyle', 'motivation', 'dailylife', 'positivevibes', 'livingmybest'],
  productivity:   ['productivity', 'timemanagement', 'focus', 'deepwork', 'habits'],
  minimalism:     ['minimalism', 'simplelife', 'declutter', 'lessismore', 'minimalist'],
  luxury:         ['luxury', 'luxurylife', 'lifestyle', 'wealth', 'highend'],
  'self-improvement': ['selfimprovement', 'personalgrowth', 'mindset', 'growthmindset', 'discipline'],
  journaling:     ['journaling', 'bulletjournal', 'journal', 'selfreflection', 'bujo'],
  stoicism:       ['stoicism', 'stoic', 'philosophy', 'marcus aurelius', 'mindset'],
  travel:         ['travel', 'wanderlust', 'adventure', 'backpacking', 'travelphotography'],
  hiking:         ['hiking', 'trailrunning', 'nature', 'outdoors', 'hikingadventures'],
  camping:        ['camping', 'outdoors', 'vanlife', 'campfire', 'campinglife'],
  photography:    ['photography', 'photographer', 'photooftheday', 'naturephotography', 'portrait'],
  'solo-travel':  ['solotravel', 'travelalone', 'solofemaletravel', 'wanderlust', 'backpacking'],
  'budget-travel':['budgettravel', 'travelcheap', 'affordabletravel', 'travelindia', 'hostel'],
  parenting:      ['parenting', 'momlife', 'dadlife', 'kidsofinstagram', 'raisingkids'],
  pets:           ['pets', 'animals', 'petstagram', 'petlover', 'animalsofinstagram'],
  dogs:           ['dogs', 'dogoftheday', 'puppylove', 'dogsofinstagram', 'doglover'],
  cats:           ['cats', 'catsofinstagram', 'catstagram', 'kittens', 'catlover'],
  relationships:  ['relationships', 'love', 'dating', 'couplegoals', 'relationshipadvice'],
  pregnancy:      ['pregnancy', 'newborn', 'baby', 'motherhood', 'momtobe'],
  art:            ['art', 'artwork', 'illustration', 'digitalart', 'artist'],
  design:         ['design', 'uiux', 'graphicdesign', 'uidesign', 'webdesign'],
  diy:            ['diy', 'crafts', 'handmade', 'makersofinstagram', 'diycrafts'],
  'interior-design': ['interiordesign', 'homedecor', 'interiors', 'homedesign', 'livingroom'],
  writing:        ['writing', 'author', 'amwriting', 'writingcommunity', 'poet'],
  architecture:   ['architecture', 'archilovers', 'design', 'urbandesign', 'modernarchitecture'],
  education:      ['education', 'learning', 'studytips', 'student', 'teacher'],
  'language-learning': ['languagelearning', 'polyglot', 'speakspanish', 'english', 'duolingo'],
  history:        ['history', 'historylovers', 'ancienthistory', 'historical', 'worldhistory'],
  philosophy:     ['philosophy', 'stoicism', 'wisdom', 'ethics', 'thinking'],
  spirituality:   ['spirituality', 'spiritual', 'manifestation', 'consciousness', 'awakening'],
}

/** Reddit subreddits per niche */
export const NICHE_SUBREDDITS = {
  finance:        ['personalfinance', 'financialindependence', 'povertyfinance'],
  investing:      ['investing', 'stocks', 'dividends'],
  crypto:         ['CryptoCurrency', 'Bitcoin', 'ethereum'],
  ecommerce:      ['ecommerce', 'dropship', 'Entrepreneur'],
  marketing:      ['marketing', 'digital_marketing', 'SEO'],
  'side-hustle':  ['sidehustle', 'beermoney', 'Entrepreneur'],
  'real-estate':  ['realestateinvesting', 'realestate', 'landlord'],
  startup:        ['startups', 'entrepreneur', 'SaaS'],
  career:         ['cscareerquestions', 'jobs', 'careerguidance'],
  fitness:        ['fitness', 'bodyweightfitness', 'loseit'],
  yoga:           ['yoga', 'flexibility', 'meditation'],
  running:        ['running', 'ultramarathon', 'trailrunning'],
  nutrition:      ['nutrition', 'HealthyFood', 'EatCheapAndHealthy'],
  'weight-loss':  ['loseit', 'progresspics', 'intermittentfasting'],
  'mental-health':['mentalhealth', 'anxiety', 'depression'],
  meditation:     ['meditation', 'Mindfulness', 'spirituality'],
  veganism:       ['vegan', 'veganfitness', 'PlantBasedDiet'],
  bodybuilding:   ['bodybuilding', 'powerlifting', 'weightlifting'],
  beauty:         ['SkincareAddiction', 'beauty', 'MakeupAddiction'],
  skincare:       ['SkincareAddiction', 'AsianBeauty', 'tretinoin'],
  hair:           ['Hair', 'curlyhair', 'HaircareScience'],
  fashion:        ['malefashionadvice', 'femalefashionadvice', 'streetwear'],
  nails:          ['RedditLaqueristas', 'nails', 'gelnails'],
  streetwear:     ['streetwear', 'Sneakers', 'hoodwink'],
  cooking:        ['Cooking', 'recipes', 'AskCulinary'],
  baking:         ['Baking', 'Breadit', 'cakedecorating'],
  'meal-prep':    ['MealPrepSunday', 'fitmeals', 'EatCheapAndHealthy'],
  food:           ['food', 'FoodPorn', 'GifRecipes'],
  keto:           ['keto', 'ketoscience', 'ketorecipes'],
  'plant-based':  ['PlantBasedDiet', 'vegan', 'whole30'],
  'street-food':  ['food', 'streetfood', 'FoodPorn'],
  coffee:         ['Coffee', 'espresso', 'barista'],
  tech:           ['technology', 'gadgets', 'techsupport'],
  ai:             ['artificial', 'MachineLearning', 'ChatGPT'],
  coding:         ['programming', 'learnprogramming', 'webdev'],
  gadgets:        ['gadgets', 'hardware', 'tech'],
  cybersecurity:  ['cybersecurity', 'netsec', 'hacking'],
  science:        ['science', 'askscience', 'Physics'],
  space:          ['space', 'Astronomy', 'spacex'],
  gaming:         ['gaming', 'pcgaming', 'indiegaming'],
  anime:          ['anime', 'manga', 'animesuggest'],
  movies:         ['movies', 'MovieSuggestions', 'horror'],
  music:          ['Music', 'indieheads', 'listentothis'],
  books:          ['books', 'booksuggestions', 'fantasy'],
  comedy:         ['funny', 'memes', 'ComedyNecrophilia'],
  sports:         ['sports', 'nba', 'soccer'],
  cricket:        ['Cricket', 'IndianCricket', 'IPL'],
  esports:        ['esports', 'leagueoflegends', 'GlobalOffensive'],
  lifestyle:      ['selfimprovement', 'productivity', 'getdisciplined'],
  productivity:   ['productivity', 'getdisciplined', 'timemanagement'],
  minimalism:     ['minimalism', 'declutter', 'simpleliving'],
  luxury:         ['luxury', 'watches', 'malelivingspace'],
  'self-improvement': ['selfimprovement', 'getdisciplined', 'decidingtobebetter'],
  journaling:     ['Journaling', 'bulletjournal', 'Diary'],
  stoicism:       ['Stoicism', 'philosophy', 'Meditations'],
  travel:         ['travel', 'solotravel', 'backpacking'],
  hiking:         ['hiking', 'ultralight', 'CampingandHiking'],
  camping:        ['camping', 'vandwellers', 'overlanding'],
  photography:    ['photography', 'photocritique', 'analog'],
  'solo-travel':  ['solotravel', 'travel', 'iwantout'],
  'budget-travel':['Shoestring', 'travel', 'solotravel'],
  parenting:      ['Parenting', 'daddit', 'Mommit'],
  pets:           ['pets', 'aww', 'AnimalsBeingBros'],
  dogs:           ['dogs', 'puppy101', 'dogtraining'],
  cats:           ['cats', 'aww', 'CatAdvice'],
  relationships:  ['relationships', 'dating_advice', 'dating'],
  pregnancy:      ['pregnant', 'beyondthebump', 'NewParents'],
  art:            ['Art', 'ArtFundamentals', 'learnart'],
  design:         ['design', 'graphic_design', 'UI_Design'],
  diy:            ['DIY', 'crafts', 'somethingimade'],
  'interior-design': ['malelivingspace', 'femalelivingspace', 'interiordesign'],
  writing:        ['writing', 'worldbuilding', 'fantasywriters'],
  architecture:   ['architecture', 'ArchitecturePorn', 'urbanplanning'],
  education:      ['education', 'Teachers', 'AskAcademia'],
  'language-learning': ['languagelearning', 'Spanish', 'learnfrench'],
  history:        ['history', 'AskHistorians', 'HistoryPorn'],
  philosophy:     ['philosophy', 'askphilosophy', 'Stoicism'],
  spirituality:   ['spirituality', 'awakened', 'meditation'],
}

/** YouTube Data API category IDs + search queries per niche */
export const NICHE_YT_CATEGORIES = {
  finance:        { id: '27', query: 'personal finance money tips 2024' },
  investing:      { id: '27', query: 'investing stocks beginner guide' },
  crypto:         { id: '27', query: 'cryptocurrency bitcoin investing 2024' },
  ecommerce:      { id: '27', query: 'ecommerce dropshipping online business' },
  marketing:      { id: '27', query: 'digital marketing social media growth' },
  'side-hustle':  { id: '27', query: 'side hustle make money online' },
  'real-estate':  { id: '27', query: 'real estate investing property tips' },
  startup:        { id: '27', query: 'startup founder entrepreneur advice' },
  career:         { id: '27', query: 'career advice job interview tips' },
  fitness:        { id: '17', query: 'fitness workout tips training' },
  yoga:           { id: '26', query: 'yoga beginner routine flexibility' },
  running:        { id: '17', query: 'running tips marathon training' },
  nutrition:      { id: '26', query: 'nutrition healthy eating diet guide' },
  'weight-loss':  { id: '26', query: 'weight loss transformation tips' },
  'mental-health':{ id: '26', query: 'mental health anxiety tips' },
  meditation:     { id: '26', query: 'meditation beginner guided mindfulness' },
  veganism:       { id: '26', query: 'vegan diet plant based lifestyle' },
  bodybuilding:   { id: '17', query: 'bodybuilding muscle building workout' },
  beauty:         { id: '26', query: 'beauty skincare makeup routine' },
  skincare:       { id: '26', query: 'skincare routine anti aging tips' },
  hair:           { id: '26', query: 'hair care routine growth tips' },
  fashion:        { id: '26', query: 'fashion style outfit ideas trends' },
  nails:          { id: '26', query: 'nail art tutorial designs' },
  streetwear:     { id: '26', query: 'streetwear style sneakers fashion' },
  cooking:        { id: '26', query: 'cooking recipes homemade easy meals' },
  baking:         { id: '26', query: 'baking bread cakes desserts recipes' },
  'meal-prep':    { id: '26', query: 'meal prep healthy recipes week' },
  food:           { id: '26', query: 'food recipes cooking foodie' },
  keto:           { id: '26', query: 'keto diet recipes low carb' },
  'plant-based':  { id: '26', query: 'plant based vegan recipes cooking' },
  'street-food':  { id: '26', query: 'street food best places eat' },
  coffee:         { id: '26', query: 'coffee latte art espresso guide' },
  tech:           { id: '28', query: 'technology ai gadgets 2024' },
  ai:             { id: '28', query: 'artificial intelligence ai tools 2024' },
  coding:         { id: '28', query: 'programming tutorial beginner web dev' },
  gadgets:        { id: '28', query: 'best gadgets tech review 2024' },
  cybersecurity:  { id: '28', query: 'cybersecurity hacking ethical tutorial' },
  science:        { id: '28', query: 'science explained facts discoveries' },
  space:          { id: '28', query: 'space astronomy nasa discoveries' },
  gaming:         { id: '20', query: 'gaming tips esports guide' },
  anime:          { id: '1',  query: 'anime review recommendations 2024' },
  movies:         { id: '1',  query: 'movie review best films' },
  music:          { id: '10', query: 'music new releases hits 2024' },
  books:          { id: '27', query: 'book review recommendations reading' },
  comedy:         { id: '23', query: 'comedy funny video stand up' },
  sports:         { id: '17', query: 'sports highlights best moments' },
  cricket:        { id: '17', query: 'cricket IPL highlights tips' },
  esports:        { id: '20', query: 'esports tournament highlights gameplay' },
  lifestyle:      { id: '26', query: 'lifestyle daily routine habits' },
  productivity:   { id: '27', query: 'productivity habits time management' },
  minimalism:     { id: '26', query: 'minimalism simple living declutter' },
  luxury:         { id: '26', query: 'luxury lifestyle rich living' },
  'self-improvement': { id: '26', query: 'self improvement discipline habits' },
  journaling:     { id: '26', query: 'journaling bullet journal tips' },
  stoicism:       { id: '27', query: 'stoicism philosophy marcus aurelius' },
  travel:         { id: '19', query: 'travel adventure destinations guide' },
  hiking:         { id: '19', query: 'hiking trails tips beginners' },
  camping:        { id: '19', query: 'camping guide gear tips' },
  photography:    { id: '2',  query: 'photography tips camera techniques' },
  'solo-travel':  { id: '19', query: 'solo travel tips safety guide' },
  'budget-travel':{ id: '19', query: 'budget travel cheap flights save' },
  parenting:      { id: '26', query: 'parenting tips newborn toddler' },
  pets:           { id: '15', query: 'pets care tips cute animals' },
  dogs:           { id: '15', query: 'dog training tips puppy care' },
  cats:           { id: '15', query: 'cat care tips training behavior' },
  relationships:  { id: '26', query: 'relationship advice dating tips' },
  pregnancy:      { id: '26', query: 'pregnancy tips newborn baby care' },
  art:            { id: '27', query: 'art tutorial digital illustration' },
  design:         { id: '27', query: 'ui ux design tutorial figma' },
  diy:            { id: '26', query: 'diy crafts projects home' },
  'interior-design': { id: '26', query: 'interior design home decor ideas' },
  writing:        { id: '27', query: 'creative writing tips author advice' },
  architecture:   { id: '26', query: 'architecture design buildings amazing' },
  education:      { id: '27', query: 'education learning study techniques' },
  'language-learning': { id: '27', query: 'language learning fluency tips' },
  history:        { id: '27', query: 'history facts ancient civilizations' },
  philosophy:     { id: '27', query: 'philosophy explained life wisdom' },
  spirituality:   { id: '26', query: 'spirituality meditation consciousness' },
}
